/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as TeamRouteImport } from './routes/team'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganiserIndexRouteImport } from './routes/organiser/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as OrganiserPayoutsRouteImport } from './routes/organiser/payouts'
import { Route as EventsSlugRouteImport } from './routes/events/$slug'
import { Route as DashboardWishlistRouteImport } from './routes/dashboard/wishlist'
import { Route as DashboardTicketsRouteImport } from './routes/dashboard/tickets'
import { Route as DashboardReviewsRouteImport } from './routes/dashboard/reviews'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard/notifications'
import { Route as DashboardNetworkRouteImport } from './routes/dashboard/network'
import { Route as CategoriesSlugRouteImport } from './routes/categories/$slug'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminRefundsRouteImport } from './routes/admin/refunds'
import { Route as AdminEventsRouteImport } from './routes/admin/events'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as OrganiserEventsIndexRouteImport } from './routes/organiser/events/index'
import { Route as OrganiserEventsCreateRouteImport } from './routes/organiser/events/create'
import { Route as OrganiserEventsEventIdEditRouteImport } from './routes/organiser/events/$eventId/edit'
import { Route as OrganiserEventsEventIdCheckinRouteImport } from './routes/organiser/events/$eventId/checkin'
import { Route as OrganiserEventsEventIdAttendeesRouteImport } from './routes/organiser/events/$eventId/attendees'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganiserIndexRoute = OrganiserIndexRouteImport.update({
  id: '/organiser/',
  path: '/organiser/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganiserPayoutsRoute = OrganiserPayoutsRouteImport.update({
  id: '/organiser/payouts',
  path: '/organiser/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWishlistRoute = DashboardWishlistRouteImport.update({
  id: '/dashboard/wishlist',
  path: '/dashboard/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTicketsRoute = DashboardTicketsRouteImport.update({
  id: '/dashboard/tickets',
  path: '/dashboard/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReviewsRoute = DashboardReviewsRouteImport.update({
  id: '/dashboard/reviews',
  path: '/dashboard/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/dashboard/profile',
  path: '/dashboard/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/dashboard/notifications',
  path: '/dashboard/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardNetworkRoute = DashboardNetworkRouteImport.update({
  id: '/dashboard/network',
  path: '/dashboard/network',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRefundsRoute = AdminRefundsRouteImport.update({
  id: '/admin/refunds',
  path: '/admin/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/admin/events',
  path: '/admin/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganiserEventsIndexRoute = OrganiserEventsIndexRouteImport.update({
  id: '/organiser/events/',
  path: '/organiser/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganiserEventsCreateRoute = OrganiserEventsCreateRouteImport.update({
  id: '/organiser/events/create',
  path: '/organiser/events/create',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganiserEventsEventIdEditRoute =
  OrganiserEventsEventIdEditRouteImport.update({
    id: '/organiser/events/$eventId/edit',
    path: '/organiser/events/$eventId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganiserEventsEventIdCheckinRoute =
  OrganiserEventsEventIdCheckinRouteImport.update({
    id: '/organiser/events/$eventId/checkin',
    path: '/organiser/events/$eventId/checkin',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganiserEventsEventIdAttendeesRoute =
  OrganiserEventsEventIdAttendeesRouteImport.update({
    id: '/organiser/events/$eventId/attendees',
    path: '/organiser/events/$eventId/attendees',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/team': typeof TeamRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/dashboard/network': typeof DashboardNetworkRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/tickets': typeof DashboardTicketsRoute
  '/dashboard/wishlist': typeof DashboardWishlistRoute
  '/events/$slug': typeof EventsSlugRoute
  '/organiser/payouts': typeof OrganiserPayoutsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/events/': typeof EventsIndexRoute
  '/organiser/': typeof OrganiserIndexRoute
  '/organiser/events/create': typeof OrganiserEventsCreateRoute
  '/organiser/events/': typeof OrganiserEventsIndexRoute
  '/organiser/events/$eventId/attendees': typeof OrganiserEventsEventIdAttendeesRoute
  '/organiser/events/$eventId/checkin': typeof OrganiserEventsEventIdCheckinRoute
  '/organiser/events/$eventId/edit': typeof OrganiserEventsEventIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/team': typeof TeamRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/dashboard/network': typeof DashboardNetworkRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/tickets': typeof DashboardTicketsRoute
  '/dashboard/wishlist': typeof DashboardWishlistRoute
  '/events/$slug': typeof EventsSlugRoute
  '/organiser/payouts': typeof OrganiserPayoutsRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/events': typeof EventsIndexRoute
  '/organiser': typeof OrganiserIndexRoute
  '/organiser/events/create': typeof OrganiserEventsCreateRoute
  '/organiser/events': typeof OrganiserEventsIndexRoute
  '/organiser/events/$eventId/attendees': typeof OrganiserEventsEventIdAttendeesRoute
  '/organiser/events/$eventId/checkin': typeof OrganiserEventsEventIdCheckinRoute
  '/organiser/events/$eventId/edit': typeof OrganiserEventsEventIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/team': typeof TeamRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/dashboard/network': typeof DashboardNetworkRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/tickets': typeof DashboardTicketsRoute
  '/dashboard/wishlist': typeof DashboardWishlistRoute
  '/events/$slug': typeof EventsSlugRoute
  '/organiser/payouts': typeof OrganiserPayoutsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/events/': typeof EventsIndexRoute
  '/organiser/': typeof OrganiserIndexRoute
  '/organiser/events/create': typeof OrganiserEventsCreateRoute
  '/organiser/events/': typeof OrganiserEventsIndexRoute
  '/organiser/events/$eventId/attendees': typeof OrganiserEventsEventIdAttendeesRoute
  '/organiser/events/$eventId/checkin': typeof OrganiserEventsEventIdCheckinRoute
  '/organiser/events/$eventId/edit': typeof OrganiserEventsEventIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy-policy'
    | '/refund-policy'
    | '/team'
    | '/terms-of-service'
    | '/admin/categories'
    | '/admin/events'
    | '/admin/refunds'
    | '/admin/users'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/categories/$slug'
    | '/dashboard/network'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/reviews'
    | '/dashboard/tickets'
    | '/dashboard/wishlist'
    | '/events/$slug'
    | '/organiser/payouts'
    | '/admin/'
    | '/dashboard/'
    | '/events/'
    | '/organiser/'
    | '/organiser/events/create'
    | '/organiser/events/'
    | '/organiser/events/$eventId/attendees'
    | '/organiser/events/$eventId/checkin'
    | '/organiser/events/$eventId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy-policy'
    | '/refund-policy'
    | '/team'
    | '/terms-of-service'
    | '/admin/categories'
    | '/admin/events'
    | '/admin/refunds'
    | '/admin/users'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/categories/$slug'
    | '/dashboard/network'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/reviews'
    | '/dashboard/tickets'
    | '/dashboard/wishlist'
    | '/events/$slug'
    | '/organiser/payouts'
    | '/admin'
    | '/dashboard'
    | '/events'
    | '/organiser'
    | '/organiser/events/create'
    | '/organiser/events'
    | '/organiser/events/$eventId/attendees'
    | '/organiser/events/$eventId/checkin'
    | '/organiser/events/$eventId/edit'
  id:
    | '__root__'
    | '/'
    | '/privacy-policy'
    | '/refund-policy'
    | '/team'
    | '/terms-of-service'
    | '/admin/categories'
    | '/admin/events'
    | '/admin/refunds'
    | '/admin/users'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/categories/$slug'
    | '/dashboard/network'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/reviews'
    | '/dashboard/tickets'
    | '/dashboard/wishlist'
    | '/events/$slug'
    | '/organiser/payouts'
    | '/admin/'
    | '/dashboard/'
    | '/events/'
    | '/organiser/'
    | '/organiser/events/create'
    | '/organiser/events/'
    | '/organiser/events/$eventId/attendees'
    | '/organiser/events/$eventId/checkin'
    | '/organiser/events/$eventId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  TeamRoute: typeof TeamRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminRefundsRoute: typeof AdminRefundsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  DashboardNetworkRoute: typeof DashboardNetworkRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardReviewsRoute: typeof DashboardReviewsRoute
  DashboardTicketsRoute: typeof DashboardTicketsRoute
  DashboardWishlistRoute: typeof DashboardWishlistRoute
  EventsSlugRoute: typeof EventsSlugRoute
  OrganiserPayoutsRoute: typeof OrganiserPayoutsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  OrganiserIndexRoute: typeof OrganiserIndexRoute
  OrganiserEventsCreateRoute: typeof OrganiserEventsCreateRoute
  OrganiserEventsIndexRoute: typeof OrganiserEventsIndexRoute
  OrganiserEventsEventIdAttendeesRoute: typeof OrganiserEventsEventIdAttendeesRoute
  OrganiserEventsEventIdCheckinRoute: typeof OrganiserEventsEventIdCheckinRoute
  OrganiserEventsEventIdEditRoute: typeof OrganiserEventsEventIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organiser/': {
      id: '/organiser/'
      path: '/organiser'
      fullPath: '/organiser/'
      preLoaderRoute: typeof OrganiserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organiser/payouts': {
      id: '/organiser/payouts'
      path: '/organiser/payouts'
      fullPath: '/organiser/payouts'
      preLoaderRoute: typeof OrganiserPayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/wishlist': {
      id: '/dashboard/wishlist'
      path: '/dashboard/wishlist'
      fullPath: '/dashboard/wishlist'
      preLoaderRoute: typeof DashboardWishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/tickets': {
      id: '/dashboard/tickets'
      path: '/dashboard/tickets'
      fullPath: '/dashboard/tickets'
      preLoaderRoute: typeof DashboardTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/reviews': {
      id: '/dashboard/reviews'
      path: '/dashboard/reviews'
      fullPath: '/dashboard/reviews'
      preLoaderRoute: typeof DashboardReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/dashboard/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/network': {
      id: '/dashboard/network'
      path: '/dashboard/network'
      fullPath: '/dashboard/network'
      preLoaderRoute: typeof DashboardNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/refunds': {
      id: '/admin/refunds'
      path: '/admin/refunds'
      fullPath: '/admin/refunds'
      preLoaderRoute: typeof AdminRefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/admin/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organiser/events/': {
      id: '/organiser/events/'
      path: '/organiser/events'
      fullPath: '/organiser/events/'
      preLoaderRoute: typeof OrganiserEventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organiser/events/create': {
      id: '/organiser/events/create'
      path: '/organiser/events/create'
      fullPath: '/organiser/events/create'
      preLoaderRoute: typeof OrganiserEventsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organiser/events/$eventId/edit': {
      id: '/organiser/events/$eventId/edit'
      path: '/organiser/events/$eventId/edit'
      fullPath: '/organiser/events/$eventId/edit'
      preLoaderRoute: typeof OrganiserEventsEventIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organiser/events/$eventId/checkin': {
      id: '/organiser/events/$eventId/checkin'
      path: '/organiser/events/$eventId/checkin'
      fullPath: '/organiser/events/$eventId/checkin'
      preLoaderRoute: typeof OrganiserEventsEventIdCheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organiser/events/$eventId/attendees': {
      id: '/organiser/events/$eventId/attendees'
      path: '/organiser/events/$eventId/attendees'
      fullPath: '/organiser/events/$eventId/attendees'
      preLoaderRoute: typeof OrganiserEventsEventIdAttendeesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  TeamRoute: TeamRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminRefundsRoute: AdminRefundsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  DashboardNetworkRoute: DashboardNetworkRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardReviewsRoute: DashboardReviewsRoute,
  DashboardTicketsRoute: DashboardTicketsRoute,
  DashboardWishlistRoute: DashboardWishlistRoute,
  EventsSlugRoute: EventsSlugRoute,
  OrganiserPayoutsRoute: OrganiserPayoutsRoute,
  AdminIndexRoute: AdminIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  OrganiserIndexRoute: OrganiserIndexRoute,
  OrganiserEventsCreateRoute: OrganiserEventsCreateRoute,
  OrganiserEventsIndexRoute: OrganiserEventsIndexRoute,
  OrganiserEventsEventIdAttendeesRoute: OrganiserEventsEventIdAttendeesRoute,
  OrganiserEventsEventIdCheckinRoute: OrganiserEventsEventIdCheckinRoute,
  OrganiserEventsEventIdEditRoute: OrganiserEventsEventIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
